#!/usr/bin/env bash
#
# Refresh data/github.yaml with the current stargazer count of sortie-ai/sortie.

set -euo pipefail

REPO="${SORTIE_REPO:-sortie-ai/sortie}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/data/github.yaml"

die() { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }
log() { printf '\033[2m%s\033[0m %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }

command -v curl >/dev/null 2>&1 || die "required command not found: curl"
command -v jq   >/dev/null 2>&1 || die "required command not found: jq"

# The count is public, so an anonymous request works. A token is still
# preferred: anonymous requests are limited to 60 per hour keyed on the
# *client IP*, and CI runners share their egress addresses with every other
# job on the same host. GITHUB_TOKEN costs nothing and needs no secret.
auth=()
if [ -n "${GH_TOKEN:-}" ]; then
    auth=(-H "Authorization: Bearer $GH_TOKEN")
    log "authenticating with GH_TOKEN"
else
    log "no GH_TOKEN set - requesting anonymously (60/hour, keyed on this IP)"
fi

hdr=$(mktemp)
trap 'rm -f "$hdr"' EXIT

# --fail-with-body is load-bearing twice over: it makes curl exit non-zero on
# 4xx and 5xx, and it still prints the body so the message below can say what
# GitHub actually objected to.
body=$(curl -sS --fail-with-body -D "$hdr" \
            "${auth[@]}" \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            "https://api.github.com/repos/$REPO") || {
    status=$(awk 'toupper($1) ~ /^HTTP/ { s = $2 } END { print s }' "$hdr")
    message=$(jq -r '.message // empty' <<<"$body" 2>/dev/null)
    # 404 deserves its own sentence: GitHub returns it rather than 403 when a
    # credential is valid but not entitled to the resource, so "not found" here
    # can equally mean "this token may not read that repository".
    case "$status" in
        404) die "GET /repos/$REPO returned 404. Either the repository was renamed, or the token in use may not read it. GitHub reports both as 404." ;;
        403|429) die "GET /repos/$REPO returned $status (rate limited or forbidden): ${message:-no message}" ;;
        *) die "GET /repos/$REPO returned HTTP ${status:-?}: ${message:-no message}" ;;
    esac
}

awk 'tolower($1) == "x-ratelimit-remaining:" { r = $2 }
     tolower($1) == "x-ratelimit-limit:"     { l = $2 }
     END { printf "rate limit: %d of %d remaining\n", r, l }' "$hdr" >&2

# `// empty` rather than `// 0`: a missing field must reach the regex below as
# an empty string and fail it, not arrive pre-laundered into a plausible zero.
stars=$(jq -r '.stargazers_count // empty' <<<"$body")

[[ "$stars" =~ ^[0-9]+$ ]] \
    || die "stargazers_count was not an integer (got '${stars:-<absent>}'). The response was probably an error object, not a repository."

# A genuine zero is not distinguishable from a parse that went wrong, and this
# repository has had stargazers since March 2026. Refuse it and let a human
# look. Delete this check if it ever fires for a real reason.
[ "$stars" -gt 0 ] \
    || die "stargazers_count is 0. Refusing to publish that; it is far more likely to be a bad parse than 121 people unstarring at once."

mkdir -p "$(dirname "$OUT")"

# No `updated:` field, deliberately. It would change on every run even when the
# count did not, so the file would never be clean, and every scheduled run
# would commit and therefore redeploy the whole site for no visible change. The
# commit date already records when the value was last refreshed.
tmp=$(mktemp)
{
    printf '# Generated by scripts/update-star-count.sh - do not edit by hand.\n'
    printf '#\n'
    printf '# Rendered by layouts/_partials/navbar.html; refreshed by\n'
    printf '# .github/workflows/star-count.yml. The value is committed so that the\n'
    printf '# build makes no network call to reproduce it.\n'
    printf 'stars: %s\n' "$stars"
} >"$tmp"
mv "$tmp" "$OUT"

log "$REPO has $stars stargazers -> ${OUT#"$ROOT"/}"
